### ISSUE TITLE
about 48net and its deploy

### ISSUE THREAD

**Issue by sparrow0629** [anson0910/CNN_face_detection#10]
hi, why there are differences between 48net's train_val.prototxt and its deploy.prototxt?
for example, no "norm layer" in deploy and a "dropout layer" which is not in train_val.prototxt below "relu3 layer"

**Comment by anson0910** [comment]
Hi!
Sorry I didn't mention that I took out the normalization layers out of the deploy.prototxt files because of convenience for me implementing them in hardware, I'll state that in the README, thanks!

I can't find inconsistency in dropout layers though...
