### ISSUE TITLE
where is the positive_1 ~ positive_15

### ISSUE THREAD

**Issue by hiyijian** [anson0910/CNN_face_detection#12]
hi @anson0910 ,
    I noticed that the positive samples are generated by aflw.py. Right? However this script only output positive_16 ~ positive_17, rather than 1-15. 
    So I wonder what script positive 1-15 are generated from?

**Comment by anson0910** [comment]
Hi hiyijian,
I used datasets such as CACD, feret, 10kUS, and Caltech before.
However, according to my experiments, using the AFLW dataset can achieve adequate accuracy.
