### ISSUE TITLE
Bug in face_preprocess_10kUS/create_negative_24c.py?

### ISSUE THREAD

**Issue by hiyijian** [anson0910/CNN_face_detection#13]
line 60-62
after calling detect_face_12c_net, no sort by confidence, then call LocalNMS which require input bboxes are sorted by confidence

is that a bug?

And would you please to share ROC on benchmark?

**Comment by anson0910** [comment]
Yes, I think that is a mistake!
Sorry... my calibration models were trained improperly, and I currently haven't found time to train them correctly, but I have fixed the training **.prototxt** files.

Previous ROC results on the FDDB were about 10% lower than the original work, but I think fixing the calibration models will reduce the difference.

**Comment by hiyijian** [comment]
sorry,  I didnt see any change in training .prototxt.

**Comment by anson0910** [comment]
The **train_val.prototxt** files of the calibration nets in **CNN_face_detection_models** were changed to have a false mirror property in the data layer.

**Comment by hiyijian** [comment]
yes. I noticed that issuse you guys discuss previously.
One more question please: line 560-563 in face_detection/face_detection_functions.py, both current_x and current_y time 2, why is that? As far as I am concerned,  current_x  and current_y are exactly the coord of top-left corner of the proposed window. there is no need to times 2?

**Comment by anson0910** [comment]
The 2 corresponds to the pooling layer of the first 12 net, since the pooling layer scales the input image down by a factor of 2.

**Comment by hiyijian** [comment]
thank you
