### ISSUE TITLE
calibrate-12 can not converge when trainning, while net-12 converged very easily

### ISSUE THREAD

**Issue by hiyijian** [anson0910/CNN_face_detection#14]
hi, @anson0910 
     I collect about 20000 faces from AFLW and 60000 backgroud patch for net-12 training.it converged very shortly after about 10000 iteration.
     However, calibrate-12 can not converge after 100000 iteration using about 2000 faces. each faces generate 45 training patches according to original paper. As a result, there are about 2000 * 45 = 100000 training samples to train calibrate-12.
     I have no clue about the problem. Can you give me some advice?

**Comment by hiyijian** [comment]
besides, I noticed that you discussed the issue in issue#4.
It seems that the performance would be better if avoiding to use crop_size and setting mirror to false.
Maybe add more training patches?

**Comment by anson0910** [comment]
Yes, adding more training patches should help, I used about 500000 positive training samples.
Another issue is how good the initialization is, which is pure luck.
If it does not converge in 50000 iterations, it is likely that it will never converge.
Sometimes it just works by restarting the training!

**Comment by hiyijian** [comment]
Thanks. I used 1000000 patches, no luck so far. I will keep trying
