### ISSUE TITLE
about the negative data

### ISSUE THREAD

**Issue by tangyudi** [anson0910/CNN_face_detection#2]
sorry to trouble,why train the 24 and 48 detect net should use the negative data from the former detect net(the rectangles from the former result) ,not the  negative data same as 12 directly?

**Comment by anson0910** [comment]
Hi, according to the paper, since the 12-net is already capable of dropping some negative candidates, the 24 and 48 nets can focus on the candidates that 12-net regard as positive samples.
It's some kind of hard negatives data mining.
