### ISSUE TITLE
Question about nms algorithm

### ISSUE THREAD

**Issue by sparrow0629** [anson0910/CNN_face_detection#21]
hi~ sorry to trouble again~
  I have a question about the nms algorithm. In your face_detection_functions.py, the "globalNMS" function has a condition at line 126, "result_rectangles[cur_rect_to_compare][5] < 0.85", which means the scale should be less than 0.85. However if you detect faces with min size 32, the scale cannot be less than 32/12. So this condition can never be true.
  So what does this condition for in this function?

**Comment by anson0910** [comment]
I think at that time, I was just playing around with whether to use IoU or IoM (intersection over min-area), and later decided to use IoU, so I changed the IoM condition to always being false...

**Comment by sparrow0629** [comment]
OK~ I got it. Thanks~
