### ISSUE TITLE
Expected result of running face_cascade_fullconv_single_crop_single_image.py script

### ISSUE THREAD

**Issue by facenx** [anson0910/CNN_face_detection#22]
Hi,

I ran face_cascade_fullconv_single_crop_single_image.py script as noticed in readme without any modifications and got this result:
![image](https://cloud.githubusercontent.com/assets/15029183/17052716/5319e4ba-5007-11e6-983e-b14af9c4e9d2.png)

Can you say if it is expected result? Or any setup should be done before running this script.

Thanks.

**Comment by anson0910** [comment]
Yes, if the threshold is set lower to have higher recall rate, more rectangles should appear.
However, as mentioned [in this issue](https://github.com/anson0910/CNN_face_detection/issues/13), the rectangles should first be sorted by confidence before NMS is performed, this is an error of mine.

**Comment by facenx** [comment]
Year. I found the absence of sorting at the end of _cal_face_24c_net_ function, but fixing doesn't appear something new:
![image](https://cloud.githubusercontent.com/assets/15029183/17063645/ff3b615e-5040-11e6-8709-9c8e42ef10d0.png)
I also played with threshold and found the best value 0.92 that leads to this result:
![image](https://cloud.githubusercontent.com/assets/15029183/17063788/b67259ae-5041-11e6-9bb9-c7b8688d6b3e.png)
As before it seems not perfect especially because of simple example and hard threshold tuning on it.
So do u see something like this on your screen, or I something do not yet know? :)

I do hope I am not putting you to too much trouble.

Thanks.

**Comment by anson0910** [comment]
Yes, I did see something like this on my screen!
No problem.

**Comment by facenx** [comment]
It seems that current quality is not enough to real usage. But code base has a big potential to create competitive detector with such production ready solutions as dlib, libccv etc.
 Thanks a lot.

**Comment by anson0910** [comment]
No problem, and thanks for your comments!
