### ISSUE TITLE
can't  find the .prototxt files

### ISSUE THREAD

**Issue by iamwx** [anson0910/CNN_face_detection#23]
hi!

Thanks for you implementation of the cascade cnn.  You are doing a great job, and i learn a lot from it.
However, i can't find some  files you mentioned in the readme, such as CNN_face_detection_models/create_lmdb_scripts/  models/face_12c/solver.prototxt.

Can you please tell me what happened? can i get that files?

thanks lot!

--
Best regards
Xing Wang

**Comment by anson0910** [comment]
Hi, you're welcome!
Sorry, forgot to mention that they are located in another repository, here's the [link](https://github.com/anson0910/CNN_face_detection_models/tree/master/create_lmdb_scripts)!

**Comment by iamwx** [comment]
I have find that files in another respository.

Thanks!
