### ISSUE TITLE
About the result after running 

### ISSUE THREAD

**Issue by MaxLingwei** [anson0910/CNN_face_detection#25]
Hello, I downloaded you project and ran in my computer. Your work helps me a lot.
A problem is that my result is shown as follow:
![2](https://cloud.githubusercontent.com/assets/14048056/18191458/16a532d4-70fd-11e6-88f0-351ec246ed6d.png)

Of course it's not good enough. I wonder it is because of my incorrect operation, or there are some bugs in your code/model? What is the result you run in you own environment? I never change your code or your caffee model.
Hope you would answer my question. Thanks a lot.

**Comment by anson0910** [comment]
Hi, you can refer to [this issue](https://github.com/anson0910/CNN_face_detection/issues/22).
The current parameters (thresholds) are not tuned at their best values, so I guess you can try tuning the parameters, for example : 
increasing the confidence value in the **detect_face_48c** method of **face_detection_functions.py**

Some other possibilities that cause these issues is there was an error during training of the calibration nets, as mentioned [here](https://github.com/anson0910/CNN_face_detection/issues/4).
The data preparation scripts have been changed as well as mentioned [here](https://github.com/anson0910/CNN_face_detection/issues/13).

**Comment by MaxLingwei** [comment]
Thank you very much.
By the way, what dataset do you use to train the calibration nets? Do you use all face in aflw? And how about the number of positive and negative train sets?

**Comment by anson0910** [comment]
Yes, I use all faces in AFLW, total images of 45 categories adding up to roughly 1 million training images.

**Comment by MaxLingwei** [comment]
I get a better result after I have modify the confidence and threshold. Later I will train a caffeemodel by myself. Thank you for your kindness!
