### ISSUE TITLE
Number of face detected in 2002/07/19/big/img_352.jpg

### ISSUE THREAD

**Issue by GabrielLin** [anson0910/CNN_face_detection#26]
I managed to run the face_cascade_fullconv_single_crop_single_image.py and got 6 faces detected in 2002/07/19/big/img_352.jpg. Is this normal? Thanks.

**Comment by anson0910** [comment]
Hi, you can refer to [this issue](https://github.com/anson0910/CNN_face_detection/issues/22).
The current parameters (thresholds) are not tuned at their best values, so I guess you can try tuning the parameters, for example : 
increasing the confidence value in the **detect_face_48c** method of **face_detection_functions.py**

Some other possibilities that cause these issues is there was an error during training of the calibration nets, as mentioned [here](https://github.com/anson0910/CNN_face_detection/issues/4).
The data preparation scripts have been changed as well as mentioned [here](https://github.com/anson0910/CNN_face_detection/issues/13).
