### ISSUE TITLE
About the training step

### ISSUE THREAD

**Issue by MaxLingwei** [anson0910/CNN_face_detection#27]
Dear anson:
I have ran you code before and now I'd like to train my own caffee model. 
But I don't understand the training step. For example, I don't know what training set I should use. According to my understanding, I should use 12*12 pixels image when I training the 12net. But in you code create_negative.py I find that you crop image to different size. I don't understand why you do so.
So I do hope you can answer my question if convenient. Thank you very much!

**Comment by anson0910** [comment]
Hi,
For the training set, you can use the AFLW dataset for positive samples, and any images without faces for negative samples.
The reason why different sizes of crops are taken from images for training is to create as many negative samples as possible from a single image, and caffe will automatically convert them to 12*12 pixel images if set properly in the prototxt file.

**Comment by MaxLingwei** [comment]
Oh, I see. Thank you very much.
And I have another question. Why do you save negative samples into different directory? Why don't just save all negative samples in the same folder?

**Comment by anson0910** [comment]
Oh, that's just for a silly reason, Nautilus on Ubuntu crashes when opening folders containing too many files, haha

**Comment by MaxLingwei** [comment]
Oh, I understand.
Thank you very much. You help me a lot.
