### ISSUE TITLE
About the face size in create_face_12c.sh

### ISSUE THREAD

**Issue by MaxLingwei** [anson0910/CNN_face_detection#29]
Dear anson,
I've read you code in create_face_12c.sh. I found that you resize the image to 60 * 60. I don't understand why you do so. And by the way why do you set the RESIZE_HEITHG and RESIZE_WIDTH both to be 15?
Hope for your answering. Thank you very much!

**Comment by anson0910** [comment]
Hi, the images created from that .sh file are actually 15 * 15, the comments were copied from **create_face_48c.sh**, sorry..
The face sizes in the lmdb are sizes of 15, such that one image can create 10 crops (top-left, top-right, bottom-left, middle, and mirrors of previous 5 crops) of sizes 12 x 12 during training.

**Comment by MaxLingwei** [comment]
So you mean that the final image used to training is also 12 * 12?

**Comment by anson0910** [comment]
The images created are of size 15 * 15, but caffe will crop blocks of sizes 12 x 12.

**Comment by MaxLingwei** [comment]
And in which step will caffe crop the image?

**Comment by anson0910** [comment]
When you perform training through executing 
`./build/tools/caffe train --solver=models/face_12c/solver.prototxt`

It's specified inside **face_12c/train_val.prototxt**

**Comment by MaxLingwei** [comment]
OK, I see. It's very nice for you to answer my question. Thany you very much!
