### ISSUE TITLE
AFLW new website can't find AFLW_Faces.txt

### ISSUE THREAD

**Issue by Max-lvl-99** [anson0910/CNN_face_detection#34]
So, I emailed the AFLW guys, and they sent me the password, and I downloaded the stuff.  However, in your aflw.py file where we are supposed to train with the AFLW dataset, at the top of the file we have: read_file_name_faces = "/home/anson/face_pictures/AFLW/AFLW_Faces.txt"    I looked through the downloads and couldn't find this AFLW_Faces.txt file anywhere.  The same holds for AFLW_Rect.txt and AFLW_sex.txt.  I was having a lot of trouble installing and using sqliteman and the other things that AFLW suggested, and was hoping to forgo that stuff and just go straight to taking the files I downloaded, putting them in the correct directory, and training the CNN.  So my question is basically: is it vital that I get sqliteman working and do all that stuff, or should the files I named above be somewhere in the tar folders I downloaded from their website?

**Comment by anson0910** [comment]
Hi,
I think you can refer to #7, melgor wrote a script and the changed **aflw.py** for the new format such that you can avoid using a GUI interface to connect to the sqlite database.

Sincerely,
Anson
