### ISSUE TITLE
train_val.prototxt about FCN

### ISSUE THREAD

**Issue by qinhuan** [anson0910/CNN_face_detection#36]
@anson0910 
Hi, can you provide train_val.prototxt file for training face12c-FCN?
I only found  CNN_face_detection_models / face_12c / face12c_full_conv.prototxt. It's used to test.
And I don't know how to write the train_val.prototxt of FCN. Forgive me..

Thank you very much!

**Comment by anson0910** [comment]
Hi,
I think you are referring to CNN_face_detection_models / face_12c / train_val.prototxt ?
Let me know if that's not what you're looking for, thanks!

**Comment by qinhuan** [comment]
Thank you for your reply!
CNN_face_detection_models / face_12c / train_val.prototxt is used to train fully connected network.
You use full conv in face_12c. Network structure is face12c_full_conv.prototxt.
I don't know how to train this full conv network. Can you help me？

**Comment by anson0910** [comment]
Hi,
Actually, training is all done on the original fully connected network, you can then use the script [here](https://github.com/anson0910/CNN_face_detection/blob/master/face_net_surgery/face_12_surgery.py) (you also need to change the variable **softQuantize** to False) to convert the net to a fully convolutional version.

For further information, you can refer to [this notebook](https://github.com/BVLC/caffe/blob/master/examples/net_surgery.ipynb), it's the same procedure. Hope that helps!
