### ISSUE TITLE
calibration_AFLW.py new code

### ISSUE THREAD

**Issue by ngksai** [anson0910/CNN_face_detection#38]
i need calibration_AFLW.py new code

**Comment by ngksai** [comment]
please provide me as early as possible

**Comment by anson0910** [comment]
Hi, what's wrong with the existing code?

**Comment by ngksai** [comment]
hi ,
in that exist code  AFLW_Faces.txt, AFLW_Rect.txt files  are not available  in the code aflw.py you previously modeified these two files with faces_anno.txt like  below link https://github.com/anson0910/CNN_face_detection/issues/7

so please provide me code for how to get files AFLW_Faces.txt, AFLW_Rect.txt  or otherwise privide me the new modified code 

Thanks&Regards
N G K Sai

**Comment by anson0910** [comment]
Hi N G K Sai,

I've uploaded the files, please see the latest commit.

Thanks,
Anson

**Comment by ngksai** [comment]
hi ,
thank you very much anson
