### ISSUE TITLE
Hi,about the train_cal accuracy and loss!

### ISSUE THREAD

**Issue by tangyudi** [anson0910/CNN_face_detection#4]
I train the 12_cal by myself but i find the loss is about 2.3 to 2.7 and the accuracy is about 0.3 after iteration 10W, is it right?

**Comment by anson0910** [comment]
Yes, the calibration nets typically do not have good accuracy.

**Comment by tangyudi** [comment]
transform_param {
    #crop_size: 12
    mean_value: 104
    mean_value: 117
    mean_value: 123
    #mirror: true	# maps [0 255] to [0 1]
  }

is the mean_value  relative to the following file?

I0411 17:56:35.388991 17623 compute_image_mean.cpp:112] Number of channels: 3
I0411 17:56:35.388999 17623 compute_image_mean.cpp:117] mean_value channel [0]:114.887
I0411 17:56:35.389019 17623 compute_image_mean.cpp:117] mean_value channel [1]:129.801
I0411 17:56:35.389024 17623 compute_image_mean.cpp:117] mean_value channel [2]:154.07

Beside, i find that if do not use the crop_size: 12 and mirror: true	the accuracy is about 0.8 for the 12_cal.

**Comment by anson0910** [comment]
_is the mean_value relative to the following file?_
Yes!

_Beside, i find that if do not use the crop_size: 12 and mirror: true the accuracy is about 0.8 for the 12_cal._
Great! The mirror attribute should not be used for calibration nets, that should be a mistake of mine.

**Comment by tangyudi** [comment]
about the 12_cal In the paper it says the sliding window is:

total:5341.8
after 12-net:426.9
after 12-calibration-net:388.7

but in your code there is no window reduce after 12-calibration-net, is there anything different?

**Comment by anson0910** [comment]
I think in the paper, it meant after 12-calibration-net, then after local-NMS, the number of windows should reduce.
The number of windows should not change after calibration.
