### ISSUE TITLE
How to get the file face12c_full_conv.caffemodel

### ISSUE THREAD

**Issue by microhua** [anson0910/CNN_face_detection#42]
Dear Anson,
I have used _face_cascade_fullconv_single_crop_single_image.py_ with files _face12c_full_conv.prototxt_ and _face12c_full_conv.caffemodel_ to detect the face in a image, it works OK.
Then I used _face_12c/solver.prototxt and face_12c/train_val.prototxt_ to train the model file _face_12c_train_iter_400000.caffemodel_(accuracy=0.882).
But I detected many faces everywhere in the image with the model file _face_12c_train_iter_400000.caffemodel_. Should I and how to get _face12c_full_conv.caffemodel_ from _face_12c_train_iter_400000.caffemodel_?
The file size of _face12c_full_conv.caffemodel_ is 28038 bytes, but the file size of _face_12c_train_iter_400000.caffemodel_ I trained is 28248 bytes.

Thanks

**Comment by anson0910** [comment]
Hi microhua,

To solve the issue of many false positives appearing, you can try tuning the thresholds.
Converting the fully connected model to a fully convolutional model only decreases the computation intensity, but should not help with lowering the number of false positives.

You can try converting by using the script [face_12_surgery.py](https://github.com/anson0910/CNN_face_detection/blob/master/face_net_surgery/face_12_surgery.py), please change the softQuantize parameter to False.
Hope that helps!

Thanks,
Anson

**Comment by microhua** [comment]
Dear Anson,

Thanks for your reply!
After I converted the file face_12c_train_iter_400000.caffemodel to a new file face12c_full_conv.caffemodel by using the script face_12_surgery.py, the face detection script is working properly.
I don't know the reason and details of it. I must study it carefully.

Thanks & Regards
microhua
