### ISSUE TITLE
concerning lmdb

### ISSUE THREAD

**Issue by sunjia2015** [anson0910/CNN_face_detection#6]
hello
I have read the paper . the input image size of the net12 is 12 ☓ 12.
however ,in your code of create_lmdb_scripts->face_12c->create_face_12c.sh,you resized the image into the size of 15. One the other hand, in the face_12c->deploy.prototxt file, the input dim is 3☓１２☓１２. could you tell me the reason?Thank you very much.

**Comment by anson0910** [comment]
Hi, I created face sizes in the lmdb with sizes of 15, such that one image can create 10 crops (top-left, top-right, bottom-left, middle, and mirrors of previous 5 crops) of sizes 12 x 12 during training.
