### ISSUE TITLE
24-net and 48-net

### ISSUE THREAD

**Issue by pby5** [anson0910/CNN_face_detection#9]
in 24-net , did you not include 12-net full connected layer?and same in 48-net, did you not include 24-net full connected layer?

**Comment by anson0910** [comment]
Yes, I didn't include them for simplicity, but you could change the prototxt files to do so!

**Comment by pby5** [comment]
thx,and when you train model, the pos and neg image number is 1:1?or neg images as many as possible?

**Comment by anson0910** [comment]
I trained with a ratio of pos : neg near 1 : 4, but I think any ratio is OK as long as the the nets don't get stuck to predicting false all the time.
